language: node_js

node_js:
  - 10.8

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn
  - yarn bootstrap

defaults: &defaults
  script:
    - yarn test:ci
    - kill $(jobs -p) || true

jobs:
  include:
    - stage: verify
      script:
        - yarn lint
    - stage: verify
      env:
        - STAGE_NAME=1x-electron
      <<: *defaults
    - stage: verify
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: verify
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: verify
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: verify
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: publish
      if: branch = master AND type = push
      env:
        - NODE_ENV=production
      script:
        - yarn build
        - echo 'Publishing master'
