dist: cypress/browsers:chrome67
language: node_js

node_js:
  - 10.8

install:
  - yarn install --frozen-lockfile

jobs:
  include:
    - stage: verify
      if: (branch = master AND type = push) OR type = pull_request
      script:
        - yarn lint
    - stage: verify
      if: (branch = master AND type = push) OR type = pull_request
      install:
        - yarn install
        - yarn bootstrap
        - yarn cypress verify
      script:
        - yarn test:ci
        - kill $(jobs -p) || true
    - stage: publish
      if: branch = master AND type = push
      env:
        - NODE_ENV=production
      install:
        - yarn install --frozen-lockfile
        - yarn bootstrap
        - yarn cypress verify
      script:
        # - yarn build
        - echo 'Publishing master'
