dist: cypress/browsers:chrome67
language: node_js

node_js:
  - 10.8

cache:
  yarn: true
  directories:
    - ~/.cache
  override:
    - yarn install --frozen-lockfile
    - yarn cypress verify

defaults: &defaults
  install:
    - yarn install
    - yarn bootstrap
    - yarn cypress verify
  script:
    - yarn test:ci
    - kill $(jobs -p) || true

jobs:
  include:
    - stage: verify
      if: (branch = master AND type = push) OR type = pull_request
      script:
        - yarn lint
    - stage: verify
      if: (branch = master AND type = push) OR type = pull_request
      env:
        - STAGE_NAME=1x-electron
      <<: *defaults
    - stage: verify
      if: (branch = master AND type = push) OR type = pull_request
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: verify
      if: (branch = master AND type = push) OR type = pull_request
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: verify
      if: (branch = master AND type = push) OR type = pull_request
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: verify
      if: (branch = master AND type = push) OR type = pull_request
      env:
        - STAGE_NAME=4x-electron
      <<: *defaults
    - stage: publish
      if: branch = master AND type = push
      env:
        - NODE_ENV=production
      install:
        - yarn install --frozen-lockfile
        - yarn bootstrap
        - yarn cypress verify
      script:
        # - yarn build
        - echo 'Publishing master'
