version: '3.6'

services:
  deps:
    build:
      context: .
      dockerfile: docker/deps.Dockerfile
      args:
        NODE_ENV: test
    working_dir: /app
    volumes:
      - .:/app

  web:
    image: node:8-alpine
    working_dir: /app
    environment:
      COMPOSE_CONVERT_WINDOWS_PATHS: $COMPOSE_CONVERT_WINDOWS_PATHS
    volumes:
      - $PWD:/app
    entrypoint:
      - yarn
      - test
    depends_on:
      - deps
