version: '3.6'

services:
  install:
    build:
      context: .
      dockerfile: docker/Dockerfile
    working_dir: /app
    volumes:
      - .:/app

  app:
    image: node:carbon-jessie
    volumes:
      - .:/app
    working_dir: /app/build/dev-server
    environment:
      NODE_ENV: development
      COMPOSE_CONVERT_WINDOWS_PATHS: $COMPOSE_CONVERT_WINDOWS_PATHS
      PORT: 80
    entrypoint:
      - yarn
      - start
    depends_on:
      - install
    ports:
      - '9000:80'
